[package]
name = "config_app"
version = "0.1.0"
edition = "2021"

[dependencies]
rian = { workspace = true, features = ["main"] }
serde_yaml.workspace = true
tokio = { workspace = true, features = ["full"] }
