[package]
name = "lib1"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "dylib"]

[dependencies]
serde = { workspace = true, features = ["derive", "rc", "std"] }

common.path = "../common"
