[package]
name = "lib1"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
anyhow.workspace = true
rian.workspace = true
serde = { workspace = true, features = ["derive", "rc", "std"] }
