[package]
name = "rian_app"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = { workspace = true, features = ["std"] }
libloading.workspace = true
rian.workspace = true
serde = { workspace = true, features = ["derive", "rc", "std"] }
