[package]
name = "replay"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools.workspace = true
serde.workspace = true
tokio = { version = "*", features = ["full"] }
tokio-stream = { version = "*", features = ["full"] }

common.path = "../common"
