[package]
name = "replay"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive", "rc", "std"] }

common.path = "../common"
tokio = { version = "*", features = ["full"] }
