[package]
name = "common"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "dylib"]

[dependencies]
anyhow.workspace = true
serde_yaml.workspace = true
tokio = { workspace = true, features = ["full"] }

rian.workspace = true
